# Project information
site_name: __package_name__
site_description: __package_description__
site_author: __author_name__
site_url: __package_doc_url__

# Repository
repo_name: 'a-slide/pycoQC'
repo_url: __package_url__

# Copyright
copyright: Copyright Â© 2020 __author_name__

# Navigation menu
nav:
    - Home: index.md
    - Installation instructions: installation.md
    - pycoQC Usage:
        - Using pycoQC: pycoQC/usage.md
        - jupyter API usage: pycoQC/API_usage.ipynb
        - Command line usage: pycoQC/CLI_usage.ipynb
    - Barcode_split Usage:
        - Using Barcode_split: Barcode_split/usage.md
        - jupyter API usage: Barcode_split/API_usage.ipynb
        - Command line usage: Barcode_split/CLI_usage.ipynb
    - Fast5_to_seq_summary Usage:
        - Using Fast5_to_seq_summary: Fast5_to_seq_summary/usage.md
        - jupyter API usage: Fast5_to_seq_summary/API_usage.ipynb
        - Command line usage: Fast5_to_seq_summary/CLI_usage.ipynb
    - Citing pycoQC: citing.md
    - Acknowledgements: acknowledgements.md
    - Alternative and complementary packages: alternative.md
    - Contributing Guidelines: contributing.md
    - Code of conduct: code_of_conduct.md
    - Licence: licence.md
    - Changelog: changelog.md

# Theme customization
theme:
    name: 'material'
    highlightjs: true
    font: false

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: a-slide
      repo: pycoQC
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - mknotebooks
